services:
  ts-tests:
    image: integritee-cli:dev
    container_name: integritee-ts-tests
    volumes:
      - ../ts-tests:/ts-tests
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on: ['integritee-node', 'integritee-worker-1', 'integritee-worker-2']
    networks:
      - integritee-test-network
    entrypoint: "dockerize -wait http://integritee-worker-2:4646/is_initialized -timeout 600s    
      /usr/local/worker-cli/ts_tests.sh 2>&1"
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge