version: "3.7"

services:
  user-shielding-key:
    image: integritee-cli:dev
    container_name: litentry-user-shielding-key
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on: ['integritee-node', 'integritee-worker-1', 'integritee-worker-2']
    networks:
      - integritee-test-network
    entrypoint: "dockerize -wait http://integritee-worker-2:4646/is_initialized -timeout 600s
      /usr/local/worker-cli/user_shielding_key.sh -p 9912 -u ws://integritee-node
      -V wss://integritee-worker-1 -A 2011 -W wss://integritee-worker-2 -B 2012 -C /usr/local/bin/integritee-cli 2>&1"
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge
