[package]
name = "lc-data-providers"
version = "0.1.0"
authors = ["Litentry Dev"]
edition = "2021"


[dependencies]
# std dependencies
hex = { version = "0.4.3", optional = true }
http = { version = "0.2", optional = true }
http_req = { optional = true, features = ["rust-tls"], branch = "master", git = "https://github.com/integritee-network/http_req" }
thiserror = { version = "1.0.26", optional = true }
url = { version = "2.0.0", optional = true }

# no_std dependencies
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# internal dependencies
itc-rest-client = { path = "../../../core/rest-client", default-features = false }

# sgx dependencies
hex-sgx = { package = "hex", git = "https://github.com/mesalock-linux/rust-hex-sgx", tag = "sgx_1.1.3", features = ["sgx_tstd"], optional = true }
http-sgx = { package = "http", git = "https://github.com/integritee-network/http-sgx.git", branch = "sgx-experimental", optional = true }
http_req-sgx = { package = "http_req", git = "https://github.com/integritee-network/http_req", default-features = false, features = ["rust-tls", "sgx"], optional = true }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", features = ["net", "thread"], optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

# litentry
litentry-primitives = { path = "../../primitives", default-features = false }

[dev-dependencies]
lc-mock-server = { path = "../mock-server" }
httpmock = "0.6"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28", default-features = false }


[features]
default = ["std"]
std = [
    "hex",
    "http",
    "http_req",
    "thiserror",
    "url",
    "itc-rest-client/std",
    "log/std",
    "serde/std",
    "serde_json/std",
    "litentry-primitives/std",
]
mockserver = []
sgx = [
    "hex-sgx",
    "http-sgx",
    "http_req-sgx",
    "thiserror_sgx",
    "url_sgx",
    "sgx_tstd",
    "itc-rest-client/sgx",
    "litentry-primitives/sgx",
]
